/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: OneSteven (https://sketchfab.com/Steven007)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/range-rover-sport-svr-956ca9d890304450bb8c448557c2c07e
title: Range Rover Sport SVR
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useLoader, useFrame } from '@react-three/fiber';
import * as THREE from 'three/build/three.module'

const handler =(e, index)=>{
  e.stopPropagation(); 
  console.log(e.eventObject.name, "GROUP:", index) 
}

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/assets/range_rover/scene.gltf');

   //>>>
   const brown_dot_texture = useLoader(THREE.TextureLoader, "assets/images/brown-dot.png")
   const point_texture = useLoader(THREE.TextureLoader, "assets/images/point.png")
   const space_texture = useLoader(THREE.TextureLoader, "assets/images/space/2.jpg")
   point_texture.wrapS = THREE.RepeatWrapping
   point_texture.wrapT = THREE.RepeatWrapping
   point_texture.repeat.set(10,30)
 
   const TEXTURES = {
     brown_dot: brown_dot_texture,
     point: point_texture,
     space: space_texture
   }
   const getTexture =(inp)=>{
     return TEXTURES[inp]
   }
   //<<<

   const renderTexture = () => {
    if(props.carTexture) {
      //alert("POPRPP")
      return (
        <>
          <meshStandardMaterial
            color={props.carColor}
            map={getTexture(props.carTexture)}
            needsUpdate={true}
          />
        </>
      )
    }
    return (
      <>
        <meshStandardMaterial
          color={props.carColor}
        />
      </>
    )
  }

  return (
    <group onClick={(event)=>handler(event,0)}  ref={group} {...props} dispose={null}>
      <group onClick={(event)=>handler(event,0)}  name="OSG_Scene">
        <group onClick={(event)=>handler(event,0)}  name="RootNode_(gltf_orientation_matrix)" rotation={[-Math.PI / 2, 0, 0]}>
          <group onClick={(event)=>handler(event,0)}  name="RootNode_(model_correction_matrix)">
            <group onClick={(event)=>handler(event,0)}  name="Range_Rover_Sport_SVRfbx" rotation={[Math.PI / 2, 0, 0]}>
              <group onClick={(event)=>handler(event,0)}  name="RootNode">
                <group onClick={(event)=>handler(event,0)}  name="object012" position={[0.03, 17.31, 42.67]} rotation={[0, 0, 0]} scale={[0.48, 0.48, 0.48]}>
                  <mesh
                    name="object012_Material006_0"
                    geometry={nodes.object012_Material006_0.geometry}
                    material={materials['Material.006']}
                  />
                </group>
                <group onClick={(event)=>handler(event,0)} 
                  name="object005"
                  position={[-0.03, 0.24, 113.58]}
                  rotation={[0, 0, 0]}
                  scale={[0.48, 0.48, 0.48]}>
                  <mesh
                    name="object005_white_glass_0"
                    geometry={nodes.object005_white_glass_0.geometry}
                    material={materials.white_glass}
                  />
                </group>
                <group onClick={(event)=>handler(event,0)} 
                  name="object010"
                  position={[-0.03, 0.13, 114.04]}
                  rotation={[0, 0, 0]}
                  scale={[0.48, 0.48, 0.48]}>
                  <mesh
                    name="object010_Material005_0"
                    geometry={nodes.object010_Material005_0.geometry}
                    material={materials['Material.005']}
                  />
                </group>
                <group onClick={(event)=>handler(event,0)} 
                  name="gum_08"
                  position={[0, 8, -5.57]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[1.18, 1.05, 1.05]}>
                  <mesh
                    name="gum_08_Material003_0"
                    geometry={nodes.gum_08_Material003_0.geometry}
                    material={materials['Material.003']}
                  />
                </group>
                <group onClick={(event)=>handler(event,0)}  name="object015" position={[-0.03, 0.66, 21.09]} rotation={[0, 0, 0]} scale={[0.48, 0.48, 0.48]}>
                  <mesh
                    name="object015_plastic_0"
                    geometry={nodes.object015_plastic_0.geometry}
                    material={materials.plastic}
                  />
                </group>
                <group onClick={(event)=>handler(event,0)} 
                  name="object011"
                  position={[-0.02, 33.57, -18.44]}
                  rotation={[0, 0, 0]}
                  scale={[0.48, 0.48, 0.48]}>
                  <mesh
                    name="object011_black_shiny_plastic_0"
                    geometry={nodes.object011_black_shiny_plastic_0.geometry}
                    material={nodes.object011_black_shiny_plastic_0.material}
                  />
                </group>
                <group onClick={(event)=>handler(event,0)}  name="object016" position={[0.06, 5.08, 78.76]} rotation={[0, 0, 0]} scale={[0.48, 0.48, 0.48]}>
                  <mesh
                    name="object016_FrontColor_0"
                    geometry={nodes.object016_FrontColor_0.geometry}
                    material={materials.FrontColor}
                  />
                </group>
                <group onClick={(event)=>handler(event,0)} 
                  name="object000"
                  position={[-0.03, -6.62, 21.37]}
                  rotation={[0, 0, 0]}
                  scale={[0.48, 0.48, 0.48]}>
                  <mesh
                    name="object000_Color_B04_0"
                    geometry={nodes.object000_Color_B04_0.geometry}
                    material={materials.Color_B04}
                  >
                    {renderTexture()}
                  </mesh>
                </group>
                <group onClick={(event)=>handler(event,0)} 
                  name="object002"
                  position={[-0.02, -18.65, -78.5]}
                  rotation={[0, 0, 0]}
                  scale={[0.48, 0.48, 0.48]}>
                  <mesh
                    name="object002_calipers_0"
                    geometry={nodes.object002_calipers_0.geometry}
                    material={materials.calipers}
                  />
                </group>
                <group onClick={(event)=>handler(event,0)} 
                  name="object003"
                  position={[-0.02, -9.49, 20.95]}
                  rotation={[0, 0, 0]}
                  scale={[0.48, 0.48, 0.48]}>
                  <mesh
                    name="object003_chasis_0"
                    geometry={nodes.object003_chasis_0.geometry}
                    material={materials.chasis}
                  />
                </group>
                <group onClick={(event)=>handler(event,0)}  name="object004" position={[0.07, 22.5, -5.17]} rotation={[0, 0, 0]} scale={[0.48, 0.48, 0.48]}>
                  <mesh
                    name="object004_Material002_0"
                    geometry={nodes.object004_Material002_0.geometry}
                    material={materials['Material.002']}
                  />
                </group>
                <group onClick={(event)=>handler(event,0)}  name="object006" position={[0.03, 6.43, 21.6]} rotation={[0, 0, 0]} scale={[0.48, 0.48, 0.48]}>
                  <mesh
                    name="object006_Material004_0"
                    geometry={nodes.object006_Material004_0.geometry}
                    material={materials['Material.004']}
                  />
                </group>
                <group onClick={(event)=>handler(event,0)} 
                  name="object007"
                  position={[-0.02, -5.29, -73.47]}
                  rotation={[0, 0, 0]}
                  scale={[0.48, 0.48, 0.48]}>
                  <mesh
                    name="object007_M_0020_Red_0"
                    geometry={nodes.object007_M_0020_Red_0.geometry}
                    material={materials.M_0020_Red}
                  />
                </group>
                <group onClick={(event)=>handler(event,0)}  name="object008" position={[0.03, 7.03, 21.42]} rotation={[0, 0, 0]} scale={[0.48, 0.48, 0.48]}>
                  <mesh
                    name="object008_chrome_0"
                    geometry={nodes.object008_chrome_0.geometry}
                    material={materials.chrome}
                  />
                </group>
                <group onClick={(event)=>handler(event,0)} 
                  name="object009"
                  position={[-0.03, -22.21, -73.16]}
                  rotation={[0, 0, 0]}
                  scale={[0.48, 0.48, 0.48]}>
                  <mesh
                    name="object009_dark_rim_0"
                    geometry={nodes.object009_dark_rim_0.geometry}
                    material={materials.dark_rim}
                  />
                </group>
                <group onClick={(event)=>handler(event,0)} 
                  name="wheel"
                  position={[38, -21.42, 84.78]}
                  rotation={[-1.57, 0, -Math.PI]}
                  scale={[-1.4, 1.17, 1.17]}>
                  <mesh
                    name="wheel_BreaksRedPaint001_0"
                    geometry={nodes.wheel_BreaksRedPaint001_0.geometry}
                    material={nodes.wheel_BreaksRedPaint001_0.material}
                  />
                </group>
                <group onClick={(event)=>handler(event,0)} 
                  name="wheel002"
                  position={[37.65, -23.67, 91.03]}
                  rotation={[-1.57, 0, -Math.PI]}
                  scale={[-1.4, 1.17, 1.17]}>
                  <mesh
                    name="wheel002_Material001_0"
                    geometry={nodes.wheel002_Material001_0.geometry}
                    material={nodes.wheel002_Material001_0.material}
                  />
                  <mesh
                    name="wheel002_Material007_0"
                    geometry={nodes.wheel002_Material007_0.geometry}
                    material={nodes.wheel002_Material007_0.material}
                  />
                  <mesh
                    name="wheel002_BreakDiscs001_0"
                    geometry={nodes.wheel002_BreakDiscs001_0.geometry}
                    material={nodes.wheel002_BreakDiscs001_0.material}
                  />
                  <mesh
                    name="wheel002_Chrome002_0"
                    geometry={nodes.wheel002_Chrome002_0.geometry}
                    material={nodes.wheel002_Chrome002_0.material}
                  />
                </group>
                <group onClick={(event)=>handler(event,0)} 
                  name="wheel001"
                  position={[-37.65, -23.67, 91.03]}
                  rotation={[-1.57, 0, 0]}
                  scale={[-1.4, 1.17, 1.17]}>
                  <mesh
                    name="wheel001_Material001_0"
                    geometry={nodes.wheel001_Material001_0.geometry}
                    material={nodes.wheel001_Material001_0.material}
                  />
                  <mesh
                    name="wheel001_Material007_0"
                    geometry={nodes.wheel001_Material007_0.geometry}
                    material={nodes.wheel001_Material007_0.material}
                  />
                  <mesh
                    name="wheel001_BreakDiscs001_0"
                    geometry={nodes.wheel001_BreakDiscs001_0.geometry}
                    material={nodes.wheel001_BreakDiscs001_0.material}
                  />
                  <mesh
                    name="wheel001_Chrome002_0"
                    geometry={nodes.wheel001_Chrome002_0.geometry}
                    material={nodes.wheel001_Chrome002_0.material}
                  />
                </group>
                <group onClick={(event)=>handler(event,0)} 
                  name="wheel003"
                  position={[-38, -21.42, 84.78]}
                  rotation={[-1.57, 0, -Math.PI]}
                  scale={[1.4, 1.17, 1.17]}>
                  <mesh
                    name="wheel003_BreaksRedPaint001_0"
                    geometry={nodes.wheel003_BreaksRedPaint001_0.geometry}
                    material={nodes.wheel003_BreaksRedPaint001_0.material}
                  />
                </group>
                <group onClick={(event)=>handler(event,0)} 
                  name="wheel004"
                  position={[-38, -20, -34.18]}
                  rotation={[0.64, 0, -Math.PI]}
                  scale={[1.4, 1.17, 1.17]}>
                  <mesh
                    name="wheel004_BreaksRedPaint001_0"
                    geometry={nodes.wheel004_BreaksRedPaint001_0.geometry}
                    material={nodes.wheel004_BreaksRedPaint001_0.material}
                  />
                </group>
                <group onClick={(event)=>handler(event,0)} 
                  name="wheel005"
                  position={[-37.65, -23.67, -39.71]}
                  rotation={[-1.57, 0, 0]}
                  scale={[-1.4, 1.17, 1.17]}>
                  <mesh
                    name="wheel005_Material001_0"
                    geometry={nodes.wheel005_Material001_0.geometry}
                    material={nodes.wheel005_Material001_0.material}
                  />
                  <mesh
                    name="wheel005_Material007_0"
                    geometry={nodes.wheel005_Material007_0.geometry}
                    material={nodes.wheel005_Material007_0.material}
                  />
                  <mesh
                    name="wheel005_BreakDiscs001_0"
                    geometry={nodes.wheel005_BreakDiscs001_0.geometry}
                    material={nodes.wheel005_BreakDiscs001_0.material}
                  />
                  <mesh
                    name="wheel005_Chrome002_0"
                    geometry={nodes.wheel005_Chrome002_0.geometry}
                    material={nodes.wheel005_Chrome002_0.material}
                  />
                </group>
                <group onClick={(event)=>handler(event,0)} 
                  name="wheel006"
                  position={[37.65, -23.67, -39.71]}
                  rotation={[-1.57, 0, -Math.PI]}
                  scale={[-1.4, 1.17, 1.17]}>
                  <mesh
                    name="wheel006_Material001_0"
                    geometry={nodes.wheel006_Material001_0.geometry}
                    material={nodes.wheel006_Material001_0.material}
                  />
                  <mesh
                    name="wheel006_Material007_0"
                    geometry={nodes.wheel006_Material007_0.geometry}
                    material={nodes.wheel006_Material007_0.material}
                  />
                  <mesh
                    name="wheel006_BreakDiscs001_0"
                    geometry={nodes.wheel006_BreakDiscs001_0.geometry}
                    material={nodes.wheel006_BreakDiscs001_0.material}
                  />
                  <mesh
                    name="wheel006_Chrome002_0"
                    geometry={nodes.wheel006_Chrome002_0.geometry}
                    material={nodes.wheel006_Chrome002_0.material}
                  />
                </group>
                <group onClick={(event)=>handler(event,0)} 
                  name="wheel007"
                  position={[38, -20, -34.18]}
                  rotation={[0.64, 0, -Math.PI]}
                  scale={[-1.4, 1.17, 1.17]}>
                  <mesh
                    name="wheel007_BreaksRedPaint001_0"
                    geometry={nodes.wheel007_BreaksRedPaint001_0.geometry}
                    material={nodes.wheel007_BreaksRedPaint001_0.material}
                  />
                </group>
                <group onClick={(event)=>handler(event,0)}  name="object001" position={[0.03, 6.76, 20.92]} rotation={[0, 0, 0]} scale={[0.48, 0.48, 0.48]}>
                  <mesh
                    name="object001_black_shiny_plastic_0"
                    geometry={nodes.object001_black_shiny_plastic_0.geometry}
                    material={nodes.object001_black_shiny_plastic_0.material}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
