/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Karol Miklas (https://sketchfab.com/karolmiklas)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/free-1975-porsche-911-930-turbo-8568d9d14a994b9cae59499f0dbed21e
title: FREE 1975 Porsche 911 (930) Turbo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useLoader, useFrame } from '@react-three/fiber';
import * as THREE from 'three/build/three.module'

const handler =(e, index)=>{
  e.stopPropagation(); 
  console.log(e.eventObject.name, "GROUP:", index) 
}



export default function Model(props) {
  //console.log(props.carTexture)
  const group = useRef()
  const frontRightWhell = useRef();
  const frontLeftWhell = useRef();

  const { nodes, materials } = useGLTF('assets/porsche/scene.gltf')
    //>>>
    const brown_dot_texture = useLoader(THREE.TextureLoader, "assets/images/brown-dot.png")
    const point_texture = useLoader(THREE.TextureLoader, "assets/images/point.png")
    const as = useLoader(THREE.TextureLoader, "assets/images/point.png")
    point_texture.wrapS = THREE.RepeatWrapping
    point_texture.wrapT = THREE.RepeatWrapping
    point_texture.repeat.set(10,30)
  
    const TEXTURES = {
      brown_dot: brown_dot_texture,
      point: point_texture
    }
    const getTexture =(inp)=>{
      return TEXTURES[inp]
    }
    //<<<

  const renderTexture = () => {
    if(props.carTexture) {
      //alert("POPRPP")
      return (
        <>
          <meshStandardMaterial
            color={props.carColor}
            map={getTexture(props.carTexture)}
            needsUpdate={true}
          />
        </>
      )
    }
    return (
      <>
        <meshStandardMaterial
          color={props.carColor}
        />
      </>
    )
  }

  useFrame((state, delta) => {
    // frontLeftWhell.current.rotation.x += 0.01
    // frontRightWhell.current.rotation.x += 0.01
  })
  return (
    <group onClick={(event)=>handler(event, 1)}  ref={group} {...props} dispose={null}>
      <group onClick={(event)=>handler(event, 1)}  name="OSG_Scene">
        <group onClick={(event)=>handler(event, 1)}  name="RootNode_(gltf_orientation_matrix)" rotation={[-Math.PI / 2, 0, 0]}>
          <group onClick={(event)=>handler(event, 1)}  name="RootNode_(model_correction_matrix)" scale={0.81}>
            <group onClick={(event)=>handler(event, 1)}  name="root">
              <group onClick={(event)=>handler(event, 1)}  name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                <group onClick={(event)=>handler(event, 1)}  name="Plane013_0" position={[0, 0.47, 3.12]} rotation={[-2.83, 0, Math.PI]} scale={[1, 0.96, 1]}>
                  <mesh name="mesh_0" geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
                  <mesh name="mesh_1" geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} />
                  <mesh name="mesh_2" geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle038_1" position={[-1.16, 0.56, -1.21]} rotation={[0.48, 0, 0]}>
                  <mesh name="mesh_3" geometry={nodes.mesh_3.geometry} material={nodes.mesh_3.material} />
                  <mesh name="mesh_4" geometry={nodes.mesh_4.geometry} material={nodes.mesh_4.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)} 
                ref={frontRightWhell}
                  name="Circle037_2"
                  position={[-1.02, 0.56, 1.97]}
                  rotation={[0.5, -0.29, 0.15]}
                  scale={[1, 1, 1]}>
                  <mesh name="mesh_5" geometry={nodes.mesh_5.geometry} material={nodes.mesh_5.material} />
                  <mesh name="mesh_6" geometry={nodes.mesh_6.geometry} material={nodes.mesh_6.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle034_3">
                  <mesh name="mesh_7" geometry={nodes.mesh_7.geometry} material={nodes.mesh_7.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle031_4">
                  <mesh name="mesh_8" geometry={nodes.mesh_8.geometry} material={nodes.mesh_8.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle016_5">
                  <mesh name="mesh_9" geometry={nodes.mesh_9.geometry} material={nodes.mesh_9.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)} 
                  name="Cube003_6"
                  position={[0.7, 0.51, -2.53]}
                  rotation={[0.04, -0.21, 0.01]}
                  scale={[0.24, 0.24, 0.24]}>
                  <mesh name="mesh_10" geometry={nodes.mesh_10.geometry} material={nodes.mesh_10.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle025_7" position={[0, 0.69, -2.1]}>
                  <mesh name="mesh_11" geometry={nodes.mesh_11.geometry} material={nodes.mesh_11.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle006_8">
                  <mesh name="mesh_12" geometry={nodes.mesh_12.geometry} material={nodes.mesh_12.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle012_9">
                  <mesh name="mesh_13" geometry={nodes.mesh_13.geometry} material={nodes.mesh_13.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle003_10">
                  <mesh name="mesh_14" geometry={nodes.mesh_14.geometry} material={nodes.mesh_14.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle002_11">
                  <mesh name="mesh_15" geometry={nodes.mesh_15.geometry} material={nodes.mesh_15.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle000_12">
                  <mesh 
                  name="mesh_16" 
                  geometry={nodes.mesh_16.geometry} 
                  material={materials.coat}
                  >

                 {renderTexture()}
                  </mesh>
                </group>
                <group onClick={(event)=>handler(event, 1)} 
                  name="Cylinder000_13"
                  position={[0.25, 1.33, 1.33]}
                  rotation={[0.62, 0.44, -0.1]}
                  scale={[0.01, 0.01, 0.01]}>
                  <mesh name="mesh_17" geometry={nodes.mesh_17.geometry} material={nodes.mesh_17.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle018_14">
                  <mesh name="mesh_18" geometry={nodes.mesh_18.geometry} material={nodes.mesh_18.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle061_15">
                  <mesh name="mesh_19" geometry={nodes.mesh_19.geometry} material={nodes.mesh_19.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)} 
                  name="Cube010_16"
                  position={[0.7, 0.51, -2.53]}
                  rotation={[0.04, -0.21, 0.01]}
                  scale={[0.24, 0.24, 0.24]}>
                  <mesh name="mesh_20" geometry={nodes.mesh_20.geometry} material={nodes.mesh_20.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)} 
                  name="Cube009_17"
                  position={[0.7, 0.51, -2.53]}
                  rotation={[0.04, -0.21, 0.01]}
                  scale={[0.24, 0.24, 0.24]}>
                  <mesh name="mesh_21" geometry={nodes.mesh_21.geometry} material={nodes.mesh_21.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)} 
                  name="Cube007_18"
                  position={[0.66, 0.48, 3.11]}
                  rotation={[0.16, 0.1, -0.02]}
                  scale={[0.91, 0.91, 0.91]}>
                  <mesh name="mesh_22" geometry={nodes.mesh_22.geometry} material={nodes.mesh_22.material} />
                  <mesh name="mesh_23" geometry={nodes.mesh_23.geometry} material={nodes.mesh_23.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle041_19">
                  <mesh name="mesh_24" geometry={nodes.mesh_24.geometry} material={nodes.mesh_24.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)} 
                  name="Cylinder006_20"
                  position={[-1.01, 1.26, 1.5]}
                  rotation={[0.05, 0, 0.05]}
                  scale={[0.01, 0.01, 0.01]}>
                  <mesh name="mesh_25" geometry={nodes.mesh_25.geometry} material={nodes.mesh_25.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle060_21">
                  <mesh name="mesh_26" geometry={nodes.mesh_26.geometry} material={nodes.mesh_26.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle056_22">
                  <mesh name="mesh_27" geometry={nodes.mesh_27.geometry} material={nodes.mesh_27.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Cube004_23" position={[0.01, 1.67, 0.65]} scale={0.06}>
                  <mesh name="mesh_28" geometry={nodes.mesh_28.geometry} material={nodes.mesh_28.material} />
                  <mesh name="mesh_29" geometry={nodes.mesh_29.geometry} material={nodes.mesh_29.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)} 
                  name="Cylinder009_24"
                  position={[0.79, 0.49, -2.38]}
                  rotation={[-1.77, -0.01, -0.46]}
                  scale={[6.31, 6.31, 6.31]}>
                  <mesh name="mesh_30" geometry={nodes.mesh_30.geometry} material={nodes.mesh_30.material} />
                  <mesh name="mesh_31" geometry={nodes.mesh_31.geometry} material={nodes.mesh_31.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)} 
                  name="Plane011_25"
                  position={[0, 0.98, -2.49]}
                  rotation={[2.32, 0, -Math.PI]}
                  scale={[0.02, 0.02, 0.02]}>
                  <mesh name="mesh_32" geometry={nodes.mesh_32.geometry} material={nodes.mesh_32.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Plane010_26" position={[0, 0.87, 2.92]} rotation={[0.46, 0, 0]} scale={[0.03, 0.03, 0.03]}>
                  <mesh name="mesh_33" geometry={nodes.mesh_33.geometry} material={nodes.mesh_33.material} />
                  <mesh name="mesh_34" geometry={nodes.mesh_34.geometry} material={nodes.mesh_34.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Cube_27" position={[0.01, 1.67, 0.65]} scale={0.06}>
                  <mesh name="mesh_35" geometry={nodes.mesh_35.geometry} material={nodes.mesh_35.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)} 
                  name="Cylinder003_29"
                  position={[-0.25, 1.33, 1.32]}
                  rotation={[0.58, 0.32, -0.01]}
                  scale={[0.01, 0.01, 0.01]}>
                  <group onClick={(event)=>handler(event, 1)} 
                    name="Plane007_28"
                    position={[37.47, -1.97, 0.92]}
                    rotation={[-2.95, -1.38, -2.99]}
                    scale={[14.49, 9.23, 13.31]}>
                    <mesh name="mesh_37" geometry={nodes.mesh_37.geometry} material={nodes.mesh_37.material} />
                  </group>
                  <mesh name="mesh_36" geometry={nodes.mesh_36.geometry} material={nodes.mesh_36.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)} 
                  name="Plane002_30"
                  position={[0.63, 1.55, -1.29]}
                  rotation={[-0.35, 0.04, -0.1]}
                  scale={[0.2, 0.13, 0.19]}>
                  <mesh name="mesh_38" geometry={nodes.mesh_38.geometry} material={nodes.mesh_38.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)} 
                  name="Plane001_31"
                  position={[0.67, 1.36, 1.11]}
                  rotation={[0.07, -1.09, -0.48]}
                  scale={[0.2, 0.13, 0.18]}>
                  <mesh name="mesh_39" geometry={nodes.mesh_39.geometry} material={nodes.mesh_39.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)} 
                  name="Cylinder002_32"
                  position={[0.32, 1.39, -1.83]}
                  rotation={[-0.51, -0.83, -0.19]}
                  scale={[0.01, 0.01, 0.01]}>
                  <mesh name="mesh_40" geometry={nodes.mesh_40.geometry} material={nodes.mesh_40.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Plane003_33" position={[0, 0.68, -2.62]} scale={[1, 0.96, 1]}>
                  <mesh name="mesh_41" geometry={nodes.mesh_41.geometry} material={nodes.mesh_41.material} />
                  <mesh name="mesh_42" geometry={nodes.mesh_42.geometry} material={nodes.mesh_42.material} />
                  <mesh name="mesh_43" geometry={nodes.mesh_43.geometry} material={nodes.mesh_43.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle040_34">
                  <mesh name="mesh_44" geometry={nodes.mesh_44.geometry} material={nodes.mesh_44.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Plane009_35" rotation={[0, -0.05, 0.15]} scale={[0.72, 0.82, 0.82]}>
                  <mesh name="mesh_45" geometry={nodes.mesh_45.geometry} material={nodes.mesh_45.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)} 
                  name="Plane004_36"
                  position={[0, 1.05, 1.38]}
                  rotation={[0, -0.05, 0.15]}
                  scale={[0.72, 0.82, 0.82]}>
                  <mesh name="mesh_46" geometry={nodes.mesh_46.geometry} material={nodes.mesh_46.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}
                  ref={frontLeftWhell}
                  name="Circle051_37"
                  position={[1.02, 0.56, 1.97]}
                  rotation={[0.52, -0.28, 0.16]}
                  scale={[1, 1, 1]}>
                  <mesh name="mesh_47" geometry={nodes.mesh_47.geometry} material={nodes.mesh_47.material} />
                  <mesh name="mesh_48" geometry={nodes.mesh_48.geometry} material={nodes.mesh_48.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle024_38">
                  <mesh name="mesh_49" geometry={nodes.mesh_49.geometry} material={nodes.mesh_49.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Plane_39">
                  <mesh name="mesh_50" geometry={nodes.mesh_50.geometry} material={nodes.mesh_50.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle036_40">
                  <mesh
                    name="mesh_51"
                    geometry={nodes.mesh_51.geometry}
                    material={materials['930_lights_refraction']}
                  />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle035_41">
                  <mesh name="mesh_52" geometry={nodes.mesh_52.geometry} material={nodes.mesh_52.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle033_42">
                  <mesh name="mesh_53" geometry={nodes.mesh_53.geometry} material={nodes.mesh_53.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle030_43">
                  <mesh name="mesh_54" geometry={nodes.mesh_54.geometry} material={nodes.mesh_54.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle027_44" scale={1}>
                  <mesh name="mesh_55" geometry={nodes.mesh_55.geometry} material={nodes.mesh_55.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle026_45">
                  <mesh name="mesh_56" geometry={nodes.mesh_56.geometry} material={nodes.mesh_56.material}>
                    
                  </mesh>
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle020_46">
                  <mesh name="mesh_57" geometry={nodes.mesh_57.geometry} material={nodes.mesh_57.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle010_47">
                  <mesh name="mesh_58" geometry={nodes.mesh_58.geometry} material={nodes.mesh_58.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle009_48">
                  <mesh name="mesh_59" geometry={nodes.mesh_59.geometry} material={nodes.mesh_59.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle001_49">
                  <mesh name="mesh_60" geometry={nodes.mesh_60.geometry} material={nodes.mesh_60.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)} 
                  name="Cube006_50"
                  position={[1.08, 1.21, 0.93]}
                  rotation={[0, 0, -0.06]}
                  scale={[0.93, 0.93, 0.93]}>
                  <mesh name="mesh_61" geometry={nodes.mesh_61.geometry} material={nodes.mesh_61.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)} 
                  name="Circle050_51"
                  position={[1.16, 0.56, -1.21]}
                  rotation={[0.48, 0, 0]}
                  scale={[0.89, 0.94, 0.94]}>
                  <mesh name="mesh_62" geometry={nodes.mesh_62.geometry} material={nodes.mesh_62.material} />
                  <mesh name="mesh_63" geometry={nodes.mesh_63.geometry} material={nodes.mesh_63.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)} 
                  name="Circle048_52"
                  position={[1.02, 0.56, 1.97]}
                  rotation={[0.52, -0.28, 0.16]}
                  scale={[1, 1, 1]}>
                  <mesh name="mesh_64" geometry={nodes.mesh_64.geometry} material={nodes.mesh_64.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Plane005_53" position={[0, 1.58, 0.67]}>
                  <mesh name="mesh_65" geometry={nodes.mesh_65.geometry} material={materials['930_wunderbaum']} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle007_54" position={[0, 0.69, -2.1]}>
                  <mesh name="mesh_66" geometry={nodes.mesh_66.geometry} material={nodes.mesh_66.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle017_55" position={[-1.8, 0.14, 3.2]}>
                  <mesh name="mesh_67" geometry={nodes.mesh_67.geometry} material={nodes.mesh_67.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle004_56">
                  <mesh name="mesh_68" geometry={nodes.mesh_68.geometry} material={nodes.mesh_68.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle005_57" position={[0, 0.89, 4.01]}>
                  <mesh name="mesh_69" geometry={nodes.mesh_69.geometry} material={nodes.mesh_69.material}>
                    
                  </mesh>
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle008_58" position={[0, 0.9, -3.5]}>
                  <mesh name="mesh_70" geometry={nodes.mesh_70.geometry} material={nodes.mesh_70.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle011_59" position={[1.8, 0.14, 3.2]}>
                  <mesh name="mesh_71" geometry={nodes.mesh_71.geometry} material={nodes.mesh_71.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle013_60">
                  <mesh name="mesh_72" geometry={nodes.mesh_72.geometry} material={nodes.mesh_72.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Circle014_61">
                  <mesh name="mesh_73" geometry={nodes.mesh_73.geometry} material={nodes.mesh_73.material} />
                </group>
                <group onClick={(event)=>handler(event, 1)}  name="Plane015_62" position={[0, 0.14, 0.28]} scale={[1.92, 1.92, 3.84]}>
                  <mesh name="mesh_74" geometry={nodes.mesh_74.geometry} material={materials.material_0} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

// useGLTF.preload('/scene.gltf')
